---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "db-instances.labels" . | nindent 4 }}
  name: dbinstance-pgexporter-query
data:
  queries.yaml: |
{{ .Values.exporter.postgres.query | indent 4 }}