name: Integration Test

on:
  push:
    paths:
      - 'db-operator/**'
      - 'db-instances/**'
  pull_request:
    branches:
      - main
  workflow_run:
    workflows: ["Test"]
    branches: [METAL-3701/add_ci]
    types:
      - completed

jobs:
  db-operator-test:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        k8s_version: ['v1.21.6', 'v1.22.3', 'v1.23.1', 'v1.24.3']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
 
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      # The existing apparmor profile for mysql needs to be removed.
      # https://github.com/actions/virtual-environments/issues/181
      # https://github.com/moby/moby/issues/7512#issuecomment-51845976
      - name: Remove MySQL App Armour Configuration
        run: |
          set -x
          sudo apt-get remove mysql-server --purge
          sudo apt-get install apparmor-profiles
          sudo apparmor_parser -R /etc/apparmor.d/usr.sbin.mysqld
      
      - name: Create k3d cluster
        env:
          K8S_VERSION: ${{ matrix.k8s_version }}
        run: make k3d
      
      - name: Install Helm chart
        run: make helm
      
      # - name: Integration test
      #   run: ./integration/test.sh