name: Test

on:
  push:
    branches:
      - METAL-3701/add_ci
  pull_request:
    branches:
      - main

jobs:
  lint: 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - id: get-chart
        name: 'Get modified charts'
        run: |
          files_changed="$(git show --pretty="" --name-only)"
          # Adding || true to avoid "Process exited with code 1" errors
          charts_dirs_changed="$(echo "$files_changed" | xargs dirname | grep -v ".github" | tr '\n' ' ' || true)"
          echo "changed:${charts_dirs_changed}"
          echo "::set-output name=CHANGED_CHARTS::${charts_dirs_changed}"

      - name: Get changed charts
        run: echo "The selected color is ${{ steps.get-chart.outputs.CHANGED_CHARTS }}"

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.9.4

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.3.0

      - name: Run chart-testing (lint)
        run: ct lint --validate-maintainers=false --target-branch main --chart-dirs .